arr = [
  { item: "I do just enough work to get by", response: "Slightly Agree" },
  { item: "I am always on the go", response: "Neutral" },
  { item: "I dislike changes", response: "Slightly Agree" },
  { item: "I contradict others", response: "Slightly Agree" },
  { item: "I seldom get mad", response: "Slightly Agree" },
  { item: "I panic easily", response: "Slightly Agree" },
  { item: "I do not enjoy going to art museums", response: "Agree" },
  { item: "I keep in the background", response: "Agree" },
  { item: " I rush into things", response: "Agree" },
  { item: "I laugh my way through life", response: "Slightly Agree" },
  { item: " I have a sharp tongue", response: "Neutral" },
  { item: "I break rules", response: "Slightly Agree" },
  { item: "I seldom get emotional", response: "Agree" },
  { item: "I act wild and crazy", response: "Neutral" },
  { item: "I avoid contacts with others", response: "Slightly Agree" },
  { item: " I love large parties", response: "Neutral" },
  { item: "I enjoy wild flights of fantasy", response: "Slightly Disagree" },
  { item: "I easily resist temptations", response: "Slightly Agree" },
  { item: "I love to read challenging material", response: "Agree" },
  {
    item: "I believe that we coddle criminals too much",
    response: "Slightly Agree",
  },
  { item: "I have a high opinion of myself", response: "Slightly Disagree" },
  { item: " I use flattery to get ahead", response: "Slightly Agree" },
  { item: " I leave a mess in my room", response: "Slightly Agree" },
  {
    item: "I am comfortable in unfamiliar situations",
    response: "Slightly Disagree",
  },
  { item: "I start tasks right away", response: "Disagree" },
  { item: "I misjudge situations", response: "Slightly Agree" },
  { item: "I can not stand weak people", response: "Neutral" },
  { item: "I distrust people.", response: "Agree" },
  {
    item: "I feel that I am unable to deal with things",
    response: "Slightly Agree",
  },
];
